#!/bin/bash

# Create if needed and cd into wp.box home directory.
WP_BOX_HOME="$HOME/wp.box"
mkdir -p "$WP_BOX_HOME"

# Show wp.box home directory content
du -h --max-depth=1 -L "$WP_BOX_HOME" | grep -v "$WP_BOX_HOME"$ 

# Done
exit
